### ISSUE TITLE
Find on the page broken on IOS8 Safari

### ISSUE THREAD

**Issue by kaihendry** [cheeaun/hackerweb#36] opened 2014-10-16 02:46 UTC
When I open the comments and search for a keyword, it doesn't scroll to that keyword.

**Comment by cheeaun** [comment] 2015-07-15 00:58
Looks like this bug is still not fixed in iOS9 (public beta). I've reported the bug via Feedback app. Let's see.

**Comment by cheeaun** [comment] 2020-05-16 13:57
Unable to reproduce now 😄

**Closed by cheeaun** 2020-05-16 13:57 UTC
Labels: bug
